set nocompatible

call plug#begin()
Plug 'lervag/vimtex'
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-sleuth'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'NLKNguyen/papercolor-theme'
call plug#end()

set shortmess+=I 
set clipboard=unnamedplus
set mouse=a
set encoding=UTF-8
set number
set modeline modelines=5
set shell=/bin/bash
set nobackup noswapfile
set wrap linebreak
set cursorline

let mapleader=' '
let maplocalleader=','

let g:vimtex_view_general_viewer = 'evince'
let g:vimtex_compiler_latexmk = {
    \ 'out_dir' : 'build',
    \ 'jobname' : 'build/main',
    \}

nnoremap <leader><leader> :NERDTreeToggleVCS<cr>
nnoremap <m-h> <c-w>h
nnoremap <m-j> <c-w>j
nnoremap <m-k> <c-w>k
nnoremap <m-l> <c-w>l
nnoremap <m-v> :vert rightb term ++close<cr>
nnoremap <m-b> :term ++close<cr>

tnoremap <Esc><Esc> <C-\><C-n>
tnoremap <m-h> <c-w>h
tnoremap <m-j> <c-w>j
tnoremap <m-k> <c-w>k
tnoremap <m-l> <c-w>l
tnoremap <m-v> <c-w>:vert rightb term ++close<cr>
tnoremap <m-b> <c-w>:term ++close<cr>

nnoremap j gj
nnoremap k gk

set bg=light
let g:airline_theme='papercolor'
silent! colorscheme PaperColor
