call plug#begin()
Plug 'preservim/nerdtree'
call plug#end()

set mouse=a
set encoding=UTF-8
set number
set modeline modelines=5
set shell=/bin/bash
set nobackup noswapfile

let mapleader=' '

nnoremap <leader><leader> :NERDTreeToggleVCS<cr>
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
nnoremap <c-t> :vert botright term ++close<cr>

tnoremap <c-h> <c-w>h
tnoremap <c-j> <c-w>j
tnoremap <c-k> <c-w>k
tnoremap <c-l> <c-w>l
tnoremap <c-t> <c-w>:vert botright term ++close<cr>
